import { loadSkillMarkdown } from "./skill-file";
import { invokeAnthropic } from "./providers/anthropic";
import { CloudflareQuotaExceededError, invokeCloudflare } from "./providers/cloudflare";
import type { SkillProvider } from "./providers/types";
import type { SkillInvocationContext, SkillInvocationResult } from "./types";

// Throws at import time if any references/*.md the Skill routes to is missing.
// Phase 1 is expected to throw here until those files exist (see skill-file.ts) —
// this module must never be imported by a code path that runs in production
// without them, since the Skill cannot safely quote a price without offer-config.md.
const SKILL_MARKDOWN = loadSkillMarkdown();

const PROVIDERS: Record<string, SkillProvider> = {
  anthropic: invokeAnthropic,
  cloudflare: invokeCloudflare,
};

// Prefix identifying a parse_failure caused specifically by "no AI provider
// was reachable" (as opposed to a bad/unparseable output from a provider
// that DID respond). Only this specific failure is worth automatically
// retrying later — see isRetryableProviderUnavailable / send-ai-reply.ts.
const PROVIDER_UNAVAILABLE_RETRY_MARKER = "provider_unavailable_retry_after_quota_reset";

/**
 * True only when invokeSkill() failed because no AI provider could be
 * reached at all (Cloudflare quota-exhausted and no usable fallback) — never
 * for a provider that responded but produced bad output. send-ai-reply.ts
 * uses this to decide whether to reschedule the same message for later
 * instead of treating it as a terminal failure.
 */
export function isRetryableProviderUnavailable(result: SkillInvocationResult): boolean {
  return result.status === "parse_failure" && result.reason.startsWith(PROVIDER_UNAVAILABLE_RETRY_MARKER);
}

/**
 * Cloudflare's free-tier neuron quota resets on a fixed 00:00 UTC
 * calendar-day boundary, not a rolling 24h window from the failure
 * (confirmed via developers.cloudflare.com/workers-ai/platform/limits/).
 * A small random jitter (0-5 min) spreads out a backlog of messages that
 * all failed on the same day, instead of every deferred retry hammering
 * Cloudflare at the exact same instant the quota resets.
 */
export function nextCloudflareQuotaResetAt(now: Date = new Date()): Date {
  const next = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + 1, 0, 0, 0, 0));
  const jitterMs = Math.random() * 5 * 60_000;
  return new Date(next.getTime() + jitterMs);
}

/**
 * AI_PROVIDER selects which underlying AI API generates replies —
 * "cloudflare" or "anthropic". Unset or unrecognized falls back to
 * "anthropic" (the original, historically-known-good provider) rather than
 * guessing. Both providers implement the identical Skill contract (same
 * SKILL_MARKDOWN, same extraction prompt, same SkillDecision validation) —
 * swapping providers is only ever this one env var, never a code change.
 *
 * If Cloudflare itself is unavailable (rate-limited or its daily free-tier
 * neuron quota is exhausted — CloudflareQuotaExceededError), this falls
 * back to Anthropic automatically for that one request, using the same
 * context and SKILL_MARKDOWN, so the reply is generated by an identical
 * Skill invocation either way. If Anthropic isn't configured or also fails,
 * no reply is invented — a parse_failure is returned so the message is
 * recorded but not silently dropped after burning all task retries against
 * a quota that can't recover until Cloudflare's daily reset. Any other kind
 * of provider error (network blip, malformed output, etc.) is untouched —
 * it behaves exactly as before this fallback existed.
 */
export async function invokeSkill(
  context: SkillInvocationContext,
): Promise<SkillInvocationResult> {
  const providerName = process.env.AI_PROVIDER ?? "anthropic";
  const provider = PROVIDERS[providerName] ?? invokeAnthropic;

  try {
    return await provider(context, SKILL_MARKDOWN);
  } catch (err) {
    if (!(err instanceof CloudflareQuotaExceededError)) {
      // Not a quota/rate-limit failure — preserve existing behavior and let
      // it propagate for Trigger.dev's normal task-level retry.
      throw err;
    }

    console.error("invokeSkill: Cloudflare unavailable, attempting fallback", { reason: err.message });

    if (!process.env.ANTHROPIC_API_KEY) {
      console.error(
        "invokeSkill: no fallback provider available (ANTHROPIC_API_KEY not set) — will retry this message after Cloudflare's daily quota reset instead of generating a reply now",
      );
      return {
        status: "parse_failure",
        reason: `${PROVIDER_UNAVAILABLE_RETRY_MARKER}: ${err.message}; no fallback provider configured`,
        rawOutput: "",
      };
    }

    try {
      const fallbackResult = await invokeAnthropic(context, SKILL_MARKDOWN);
      console.log("invokeSkill: Anthropic fallback succeeded", { status: fallbackResult.status });
      return fallbackResult;
    } catch (fallbackErr) {
      const fallbackReason = fallbackErr instanceof Error ? fallbackErr.message : String(fallbackErr);
      console.error("invokeSkill: Anthropic fallback also failed", { reason: fallbackReason });
      return {
        status: "parse_failure",
        reason: `provider_unavailable: ${err.message}; fallback to Anthropic also failed: ${fallbackReason}`,
        rawOutput: "",
      };
    }
  }
}
